apiVersion: v2
name: inteli-api
appVersion: '1.0.0'
description: A Helm chart for inteli-api
version: '1.0.0'
type: application
maintainers:
  - name: digicatapult
    email: opensource@digicatapult.org.uk
    url: www.digicatapult.org.uk
