config:
  port: 80
  logLevel: info
  dbName: inteli
  dbPort: 5432
image:
  repository: ghcr.io/digicatapult/inteli-api
  pullPolicy: IfNotPresent
  tag: 'v1.3.1'
  pullSecrets: ['ghcr-digicatapult']

postgresql:
  enabled: true
  postgresqlDatabase: inteli
  postgresqlUsername: postgres
  postgresqlPassword: postgres
