config:
  port: 80
  dscpApiHost: dscp-api
  dscpApiPort: 80
  logLevel: info
  dbName: inteli
  dbPort: 5432
  identityServiceHost: localhost
  identityServicePort: 80
  auth:
    jwksUri: https://inteli.eu.auth0.com/.well-known/jwks.json
    audience: inteli-dev
    issuer: https://inteli.eu.auth0.com/
    tokenUrl: https://inteli.eu.auth0.com/oauth/token

image:
  repository: ghcr.io/digicatapult/inteli-api
  pullPolicy: IfNotPresent
  tag: 'v1.8.0'
  pullSecrets: ['ghcr-digicatapult']

postgresql:
  enabled: true
  postgresqlDatabase: inteli
  postgresqlUsername: postgres
  postgresqlPassword: postgres
